-- =============================================================================
-- P&L GERENCIAL (PYL) a partir de WHOWNER.BT_MP_UNIT_ECONOMICS
-- -----------------------------------------------------------------------------
-- Saida em formato LONGO: 1 linha por (PERIODO, SITE, BU, SUBBU, PRODUCT, CAMPO_UE)
-- ja classificada nos niveis do mapping PYL:
--     N1_MARGEN    -> MARGEN_MANAGERIAL_NEW      (A., B., C., D., E., F., H.)
--     N2_SUBTOTAL  -> SUBTOTALES_MANAGERIAL_NEW  (A.1, B.5, C.17, D.19, ...)
--     N3_DETALLE   -> PYL_DETAIL_MANAGERIAL_NEW  (A.1.1, C.17.4, ...)
--     N4_UE        -> PYL_MANAGERIAL_UE_NEW / PYL_3_VARCHAR / PYL_4_VARCHAR
--
-- NADA SE PERDE:
--   * TIPO_LINEA = 'PYL'        -> linhas do P&L (e o que se soma)
--   * TIPO_LINEA = 'CONTROL_UE' -> margens que a propria UE entrega
--                                  (Product Monetization, Net Monetization, VC,
--                                  DC, BC, BM, EBIT). Servem para conciliar.
--                                  NAO somar junto com 'PYL'.
--   * TIPO_LINEA = 'RESIDUAL'   -> campos da query que nao existem no mapping.
--                                  Vao para Z.99 com o nome original do campo
--                                  e uma SUGERENCIA de onde encaixar.
--   * Qualquer campo novo que entre no UNPIVOT e nao esteja no CTE `mapa` cai
--     automaticamente em Z.99.99 (nunca desaparece silenciosamente).
--
-- Dialeto: BigQuery (UNPIVOT + GROUP BY ALL). Em outro engine, trocar o UNPIVOT
-- por UNION ALL e o ARRAY<STRUCT<>> por uma tabela/VALUES de mapeamento.
-- =============================================================================

-- Periodo: ajuste as duas datas abaixo.
-- O BigQuery nao aceita os placeholders <UE_DATE_DESDE> / <UE_DATE_HASTA> da
-- ferramenta interna. Alternativas, se preferir:
--   a) query parameters : WHERE UE_DATE BETWEEN @ue_date_desde AND @ue_date_hasta
--   b) literais diretos : WHERE UE_DATE BETWEEN DATE '2025-01-01' AND DATE '2025-12-31'
--   c) placeholders     : WHERE UE_DATE BETWEEN <UE_DATE_DESDE> AND <UE_DATE_HASTA>
--                         (so na ferramenta interna, nao no console do BQ)
-- Se UE_DATE nao for DATE (ex.: TIMESTAMP/STRING), ajuste o tipo do DECLARE.
--
-- CUSTO: a tabela e particionada por UE_DATE e o pruning funciona, entao o custo
-- e proporcional a janela de datas. Medido em dry-run (4 colunas de metrica):
--     1 mes  ->   526 GB
--     9 meses -> 11.661 GB  (~US$ 57)
-- Com as 170 colunas do P&L o volume sobe bastante. Rode mes a mes e evite
-- ranges longos sem necessidade.
DECLARE UE_DATE_DESDE DATE DEFAULT DATE_TRUNC(CURRENT_DATE(), MONTH);
DECLARE UE_DATE_HASTA DATE DEFAULT CURRENT_DATE();

WITH base AS (
  SELECT
    PERIODO,
    SIT_SITE_ID,
    UE_MP_BU_MANAGERIAL,
    UE_MP_SUBBU_MANAGERIAL,
    UE_MP_PRODUCT_MANAGERIAL,
    SUM(PROCESSING_FEE_COLLECTOR) AS PROCESSING_FEE_COLLECTOR,
    SUM(PROCESSING_FEE_PAYER) AS PROCESSING_FEE_PAYER,
    SUM(UE_MP_REVENUE_SHARE_LC) AS UE_MP_REVENUE_SHARE_LC,
    SUM(UE_MP_SPREAD_MARK_UP_AMT_LC) AS UE_MP_SPREAD_MARK_UP_AMT_LC,
    SUM(UE_MP_PROCESSING_FEE_MANUAL_AMT_LC) AS UE_MP_PROCESSING_FEE_MANUAL_AMT_LC,
    SUM(UE_MP_NETWORK_FEE_AMT_LC) AS UE_MP_NETWORK_FEE_AMT_LC,
    SUM(UE_MP_CHG_AMT_LC) AS UE_MP_CHG_AMT_LC,
    SUM(CARD_INTERCHANGE_FEES) AS CARD_INTERCHANGE_FEES,
    SUM(CARD_SPREAD) AS CARD_SPREAD,
    SUM(CARD_EXTRACTION_FEE) AS CARD_EXTRACTION_FEE,
    SUM(UE_MP_LYL_CASHBACK_TD) AS UE_MP_LYL_CASHBACK_TD,
    SUM(UE_MP_OTH_CARD_REV_AMT_LC) AS UE_MP_OTH_CARD_REV_AMT_LC,
    SUM(UE_MP_CARD_FX_ADJ_AMT_LC) AS UE_MP_CARD_FX_ADJ_AMT_LC,
    SUM(INSURTECH_FEE) AS INSURTECH_FEE,
    SUM(INSURTECH_FEE_PLATAFORMA) AS INSURTECH_FEE_PLATAFORMA,
    SUM(INSURTECH_FEE_PUBLICIDAD) AS INSURTECH_FEE_PUBLICIDAD,
    SUM(UE_MP_INSUR_DISCOUNT_AMT_LC) AS UE_MP_INSUR_DISCOUNT_AMT_LC,
    SUM(CRYPTOCURRENCY) AS CRYPTOCURRENCY,
    SUM(UE_MP_INVESTMENT_REV_AMT_LC) AS UE_MP_INVESTMENT_REV_AMT_LC,
    SUM(UE_MP_INVESTMENT_REV_MLB_AMT_LC) AS UE_MP_INVESTMENT_REV_MLB_AMT_LC,
    SUM(UE_MP_TURBINED_REV_AMT_LC) AS UE_MP_TURBINED_REV_AMT_LC,
    SUM(UE_MP_FUNDS_REV_AMT_LC) AS UE_MP_FUNDS_REV_AMT_LC,
    SUM(UE_MP_CDB_INVESTMENT_REV_AMT_LC) AS UE_MP_CDB_INVESTMENT_REV_AMT_LC,
    SUM(UE_MP_CASHBACKS_CTA_REM_AMT_LC) AS UE_MP_CASHBACKS_CTA_REM_AMT_LC,
    SUM(MONEY_IN_FEES_DA) AS MONEY_IN_FEES_DA,
    SUM(MONEY_OUT_FEE_DA) AS MONEY_OUT_FEE_DA,
    SUM(CASH_OUT_FEES_DA) AS CASH_OUT_FEES_DA,
    SUM(UE_MP_MNG_OTHER_VAR_FEES_AMT_LC) AS UE_MP_MNG_OTHER_VAR_FEES_AMT_LC,
    SUM(UE_MP_ULTRAPASSE_AMT_LC) AS UE_MP_ULTRAPASSE_AMT_LC,
    SUM(DISBURSEMENT) AS DISBURSEMENT,
    SUM(UE_MP_LYL_CASHBACK) AS UE_MP_LYL_CASHBACK,
    SUM(UE_MP_OTHER_PRODUCT_COGS_AMT_LC) AS UE_MP_OTHER_PRODUCT_COGS_AMT_LC,
    SUM(UE_MP_PRODUCT_MONETIZATION_AMT_LC) AS UE_MP_PRODUCT_MONETIZATION_AMT_LC,
    SUM(UE_MP_INSUR_PERF_BONUS_FEE_LC) AS UE_MP_INSUR_PERF_BONUS_FEE_LC,
    SUM(UE_MP_INSUR_SIGNING_BONUS_FEE_LC) AS UE_MP_INSUR_SIGNING_BONUS_FEE_LC,
    SUM(FINANCING_GROSS) AS FINANCING_GROSS,
    SUM(UE_MP_FINANCING_GROSS_MANUAL_LC) AS UE_MP_FINANCING_GROSS_MANUAL_LC,
    SUM(UE_MP_FLOATING_AMT_LC) AS UE_MP_FLOATING_AMT_LC,
    SUM(UE_MP_BLOCKED_REV_AMT_LC) AS UE_MP_BLOCKED_REV_AMT_LC,
    SUM(UE_MP_CDB_PROP_INVESTMENT_REV_AMT_LC) AS UE_MP_CDB_PROP_INVESTMENT_REV_AMT_LC,
    SUM(UE_MP_FINANCING_COST_FTP_AMT_LC) AS UE_MP_FINANCING_COST_FTP_AMT_LC,
    SUM(CASE WHEN SIT_SITE_ID = 'MLB' AND UE_MP_PRODUCT_MANAGERIAL = 'DEBIT CARD' THEN 0 ELSE UE_MP_COSTO_PLAZO_FTP_AMT_LC END) AS UE_MP_COSTO_PLAZO_FTP_AMT_LC,
    SUM(CASE WHEN SIT_SITE_ID = 'MLB' AND UE_MP_PRODUCT_MANAGERIAL = 'DEBIT CARD' THEN UE_MP_COSTO_PLAZO_FTP_AMT_LC ELSE 0 END) AS SALDOS_BLOQUEADOS_MLB,
    SUM(UE_MP_FEE_RIESGO_AMT_LC) AS UE_MP_FEE_RIESGO_AMT_LC,
    SUM(CASE WHEN TPV_SEGMENT_ID <> 'Point Device Sale' THEN SALE_TAXES ELSE 0 END) AS SALE_TAXES,
    SUM(CASE WHEN TPV_SEGMENT_ID <> 'Point Device Sale' THEN UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC ELSE 0 END) AS UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC,
    SUM(CASE WHEN TPV_SEGMENT_ID = 'Point Device Sale' THEN SALE_TAXES ELSE 0 END) AS SALE_TAXES_MPOS,
    SUM(CASE WHEN TPV_SEGMENT_ID = 'Point Device Sale' THEN UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC ELSE 0 END) AS UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC_MPOS,
    SUM(UE_MP_NET_MONETIZATION_AMT_LC) AS UE_MP_NET_MONETIZATION_AMT_LC,
    SUM(COLLECTION_COST) AS COLLECTION_COST,
    SUM(INCENTIVE_CUBO) AS INCENTIVE_CUBO,
    SUM(CHARGEBACKS) AS CHARGEBACKS,
    SUM(UE_MP_CBK_PREVISION_AMT_LC) AS UE_MP_CBK_PREVISION_AMT_LC,
    SUM(REFUND_SEL) AS REFUND_SEL,
    SUM(REFUND_BUY) AS REFUND_BUY,
    SUM(REFUND_DISPUTE) AS REFUND_DISPUTE,
    SUM(REFUND_THIRD) AS REFUND_THIRD,
    SUM(REFUND_VINCULATE) AS REFUND_VINCULATE,
    SUM(UE_MP_MNG_BAD_DEBT_AMT_LC) AS UE_MP_MNG_BAD_DEBT_AMT_LC,
    SUM(UE_MP_FUNDING_COST_FTP_AMT_LC) AS UE_MP_FUNDING_COST_FTP_AMT_LC,
    SUM(UE_MP_MNG_BPP_AMT_LC) AS UE_MP_MNG_BPP_AMT_LC,
    SUM(UE_MP_MNG_MKT_PERF_AMT_LC) AS UE_MP_MNG_MKT_PERF_AMT_LC,
    SUM(UE_MP_MNG_CX_VAR_AMT_LC) AS UE_MP_MNG_CX_VAR_AMT_LC,
    SUM(UE_MP_MNG_HST_VAR_AMT_LC) AS UE_MP_MNG_HST_VAR_AMT_LC,
    SUM(UE_MP_MNG_FRD_PREV_BURO_AMT_LC) AS UE_MP_MNG_FRD_PREV_BURO_AMT_LC,
    SUM(MONEY_IN_COST_DA) AS MONEY_IN_COST_DA,
    SUM(MONEY_OUT_COST_DA) AS MONEY_OUT_COST_DA,
    SUM(CASH_OUT_COST_DA) AS CASH_OUT_COST_DA,
    SUM(UE_MP_MONEY_OUT_FIXED_COST_AMT_LC) AS UE_MP_MONEY_OUT_FIXED_COST_AMT_LC,
    SUM(UE_MP_CASH_OUT_FIXED_COST_AMT_LC) AS UE_MP_CASH_OUT_FIXED_COST_AMT_LC,
    SUM(ATM_INQUIRY_FIXED_COST) AS ATM_INQUIRY_FIXED_COST,
    SUM(ATM_WITHDRAWAL_FIXED_COST) AS ATM_WITHDRAWAL_FIXED_COST,
    SUM(ATM_WITHDRAWAL_PERC_COST_AMT_LC) AS ATM_WITHDRAWAL_PERC_COST_AMT_LC,
    SUM(UE_MP_COSTO_ALIAS_AMT_LC) AS UE_MP_COSTO_ALIAS_AMT_LC,
    SUM(UE_MP_TARIFA_INTERBANCARIA_ATM_LC) AS UE_MP_TARIFA_INTERBANCARIA_ATM_LC,
    SUM(CARD_MASTER_COST) AS CARD_MASTER_COST,
    SUM(CARD_VISA_COST) AS CARD_VISA_COST,
    SUM(BRAND_COST_TRX) AS BRAND_COST_TRX,
    SUM(BRAND_AUTHORIZATION_FEE) AS BRAND_AUTHORIZATION_FEE,
    SUM(BRAND_CLEARING_FEE) AS BRAND_CLEARING_FEE,
    SUM(BRAND_PERC_COST_TRX_AMT_LC) AS BRAND_PERC_COST_TRX_AMT_LC,
    SUM(BRAND_PERC_COST_NO_TRX_AMT_LC) AS BRAND_PERC_COST_NO_TRX_AMT_LC,
    SUM(TOKEN_BRAND_PERC_COST_AMT_LC) AS TOKEN_BRAND_PERC_COST_AMT_LC,
    SUM(CARD_INCENTIVE_PPD) AS CARD_INCENTIVE_PPD,
    SUM(INCENTIVE_TRX_AMT_LC) AS INCENTIVE_TRX_AMT_LC,
    SUM(INCENTIVE_PERC_COST_TRX_AMT_LC) AS INCENTIVE_PERC_COST_TRX_AMT_LC,
    SUM(PRODUCTION_PROCESSING_COST) AS PRODUCTION_PROCESSING_COST,
    SUM(CONDUCTOR_COST) AS CONDUCTOR_COST,
    SUM(PROCESSING_COST_TRX) AS PROCESSING_COST_TRX,
    SUM(UE_MP_MNG_SVC_CRD_AMT_LC) AS UE_MP_MNG_SVC_CRD_AMT_LC,
    SUM(UE_MP_MNG_COMM_RSLR_AMT_LC) AS UE_MP_MNG_COMM_RSLR_AMT_LC,
    SUM(UE_MP_MNG_OTH_DIR_VAR_COST_AMT_LC) AS UE_MP_MNG_OTH_DIR_VAR_COST_AMT_LC,
    SUM(UE_MP_MNG_TLM_AMT_LC) AS UE_MP_MNG_TLM_AMT_LC,
    SUM(UE_MP_MNG_DISCOUNT_AMT_LC) AS UE_MP_MNG_DISCOUNT_AMT_LC,
    SUM(UE_MP_PAYER_DISCOUNT_AMT_LC) AS UE_MP_PAYER_DISCOUNT_AMT_LC,
    SUM(UE_MP_INCENTIVES_SELLERS_AMT_LC) AS UE_MP_INCENTIVES_SELLERS_AMT_LC,
    SUM(UE_MP_BONIFICACIONES_SELLERS_AMT_LC) AS UE_MP_BONIFICACIONES_SELLERS_AMT_LC,
    SUM(UE_MP_CUPONES_SELLER_AMT_LC) AS UE_MP_CUPONES_SELLER_AMT_LC,
    SUM(UE_MP_DISC_CBCK_PAYER_AMT_LC) AS UE_MP_DISC_CBCK_PAYER_AMT_LC,
    SUM(UE_MP_MNG_CERTIFIED_ADVISOR_AMT_LC) AS UE_MP_MNG_CERTIFIED_ADVISOR_AMT_LC,
    SUM(UE_MP_MNG_COUPONS_AMT_LC) AS UE_MP_MNG_COUPONS_AMT_LC,
    SUM(UE_MP_VC_PRICING_AMT_LC) AS UE_MP_VC_PRICING_AMT_LC,
    SUM(UE_MP_DC_PRICING_AMT_LC) AS UE_MP_DC_PRICING_AMT_LC,
    SUM(UE_MP_VARIABLE_CONTRIBUTION_EXC_FIN_ADJ_AMT_LC) AS UE_MP_VARIABLE_CONTRIBUTION_EXC_FIN_ADJ_AMT_LC,
    SUM(UE_MP_VARIABLE_CONTRIBUTION_AMT_LC) AS UE_MP_VARIABLE_CONTRIBUTION_AMT_LC,
    SUM(UE_MP_VARIABLE_CONTRIBUTION_ADJ_AMT_LC) AS UE_MP_VARIABLE_CONTRIBUTION_ADJ_AMT_LC,
    SUM(MPOS_SALE) AS MPOS_SALE,
    SUM(UE_MP_ALQUILER_MPOS_AMT_LC) AS UE_MP_ALQUILER_MPOS_AMT_LC,
    SUM(MPOS_DISCOUNT) AS MPOS_DISCOUNT,
    SUM(UE_MP_MNG_BAD_DEBIT_POINT_AMT_LC) AS UE_MP_MNG_BAD_DEBIT_POINT_AMT_LC,
    SUM(UE_MP_MNG_COST_PRD_SOLD_AMT_LC) AS UE_MP_MNG_COST_PRD_SOLD_AMT_LC,
    SUM(UE_MP_MNG_SHP_COST_POINT_AMT_LC) AS UE_MP_MNG_SHP_COST_POINT_AMT_LC,
    SUM(UE_MP_MNG_WHS_COST_POINT_AMT_LC) AS UE_MP_MNG_WHS_COST_POINT_AMT_LC,
    SUM(UE_MP_MNG_SUPP_COST_POINT_AMT_LC) AS UE_MP_MNG_SUPP_COST_POINT_AMT_LC,
    SUM(UE_MP_MNG_RECOND_AMT_LC) AS UE_MP_MNG_RECOND_AMT_LC,
    SUM(UE_MP_MNG_OTH_MPOS_COGS_AMT_LC) AS UE_MP_MNG_OTH_MPOS_COGS_AMT_LC,
    SUM(UE_MP_MNG_PREV_COST_MPOS_AMT_LC) AS UE_MP_MNG_PREV_COST_MPOS_AMT_LC,
    SUM(UE_MP_MNG_POM_POINT_AMT_LC) AS UE_MP_MNG_POM_POINT_AMT_LC,
    SUM(UE_MP_MKT_POM_SELLERS_AMT_LC) AS UE_MP_MKT_POM_SELLERS_AMT_LC,
    SUM(UE_MP_MKT_POM_ACTIVATION_AMT_LC) AS UE_MP_MKT_POM_ACTIVATION_AMT_LC,
    SUM(UE_MP_MKT_POM_ADQUISITION_AMT_LC) AS UE_MP_MKT_POM_ADQUISITION_AMT_LC,
    SUM(UE_MP_MNG_COMISIONES_RESELLERS_POINT_AMT_LC) AS UE_MP_MNG_COMISIONES_RESELLERS_POINT_AMT_LC,
    SUM(CASE WHEN TPV_SEGMENT_ID = 'Point Device Sale' THEN UE_MP_MNG_SLS_FORCE_AMT_LC ELSE 0 END) AS UE_MP_MNG_SLS_FORCE_MPOS_AMT_LC,
    SUM(CASE WHEN TPV_SEGMENT_ID <> 'Point Device Sale' THEN UE_MP_MNG_SLS_FORCE_AMT_LC ELSE 0 END) AS UE_MP_MNG_SLS_FORCE_AMT_LC,
    SUM(UE_MP_MNG_SLS_FORCE_PROPIA_AMT_LC) AS UE_MP_MNG_SLS_FORCE_PROPIA_AMT_LC,
    SUM(UE_MP_MNG_OTHER_SALES_EXPENSES_POINT_AMT_LC) AS UE_MP_MNG_OTHER_SALES_EXPENSES_POINT_AMT_LC,
    SUM(UE_MP_MNG_TELEVENTAS_AMT_LC) AS UE_MP_MNG_TELEVENTAS_AMT_LC,
    SUM(UE_MP_MNG_WEB_TERC_AMT_LC) AS UE_MP_MNG_WEB_TERC_AMT_LC,
    SUM(UE_MP_MNG_PRES_LCL_AMT_LC) AS UE_MP_MNG_PRES_LCL_AMT_LC,
    SUM(UE_MP_MNG_MGM_AMT_LC) AS UE_MP_MNG_MGM_AMT_LC,
    SUM(MONTO_EMISION_COST) AS MONTO_EMISION_COST,
    SUM(MONTO_SHIPPING_COST) AS MONTO_SHIPPING_COST,
    SUM(UE_MP_CARD_REPRINT_FEES_AMT_LC) AS UE_MP_CARD_REPRINT_FEES_AMT_LC,
    SUM(UE_MP_MNG_OTH_FIX_COST_AMT_LC) AS UE_MP_MNG_OTH_FIX_COST_AMT_LC,
    SUM(UE_MP_MNG_OTHER_FIXED_FINTECH_COSTS_AMT_LC) AS UE_MP_MNG_OTHER_FIXED_FINTECH_COSTS_AMT_LC,
    SUM(UE_MP_MNG_INI_AMT_LC) AS UE_MP_MNG_INI_AMT_LC,
    SUM(UE_MP_MNG_SPEC_DATE_AMT_LC) AS UE_MP_MNG_SPEC_DATE_AMT_LC,
    SUM(UE_MP_MNG_OTH_MKT_EXP_AMT_LC) AS UE_MP_MNG_OTH_MKT_EXP_AMT_LC,
    SUM(UE_MP_MNG_MKT_INVEST_ADJ_AMT_LC) AS UE_MP_MNG_MKT_INVEST_ADJ_AMT_LC,
    SUM(UE_MP_MNG_OTH_SLS_EXP_AMT_LC) AS UE_MP_MNG_OTH_SLS_EXP_AMT_LC,
    SUM(UE_MP_MNG_LY_CNT_SUBX_REVS_AMT_LC) AS UE_MP_MNG_LY_CNT_SUBX_REVS_AMT_LC,
    SUM(UE_MP_MNG_LY_CNT_ORG_AMT_LC) AS UE_MP_MNG_LY_CNT_ORG_AMT_LC,
    SUM(UE_MP_MNG_LY_CNT_SUBS_COST_AMT_LC) AS UE_MP_MNG_LY_CNT_SUBS_COST_AMT_LC,
    SUM(UE_MP_MNG_CX_FIX_AMT_LC) AS UE_MP_MNG_CX_FIX_AMT_LC,
    SUM(UE_MP_MNG_HST_FIX_AMT_LC) AS UE_MP_MNG_HST_FIX_AMT_LC,
    SUM(UE_MP_MNG_FRD_PREV_AMT_LC) AS UE_MP_MNG_FRD_PREV_AMT_LC,
    SUM(UE_MP_MNG_SM_LC_AMT_LC) AS UE_MP_MNG_SM_LC_AMT_LC,
    SUM(UE_MP_SHIPPING_OPS_FIXED_AMT_LC) AS UE_MP_SHIPPING_OPS_FIXED_AMT_LC,
    SUM(UE_MP_DC_AMT_LC) AS UE_MP_DC_AMT_LC,
    SUM(UE_MP_MNG_MKT_BRAND_AMT_LC) AS UE_MP_MNG_MKT_BRAND_AMT_LC,
    SUM(UE_MP_MNG_PD_DIR_AMT_LC) AS UE_MP_MNG_PD_DIR_AMT_LC,
    SUM(UE_MP_MNG_PD_INDIR_AMT_LC) AS UE_MP_MNG_PD_INDIR_AMT_LC,
    SUM(UE_MP_MNG_GNA_LC_AMT_LC) AS UE_MP_MNG_GNA_LC_AMT_LC,
    SUM(UE_MP_MNG_GNA_CORP_SUBBU_AMT_LC) AS UE_MP_MNG_GNA_CORP_SUBBU_AMT_LC,
    SUM(UE_MP_MNG_GNA_CORP_BU_AMT_LC) AS UE_MP_MNG_GNA_CORP_BU_AMT_LC,
    SUM(UE_MP_MNG_SM_CORP_SUBBU_AMT_LC) AS UE_MP_MNG_SM_CORP_SUBBU_AMT_LC,
    SUM(UE_MP_MNG_SM_CORP_BU_AMT_LC) AS UE_MP_MNG_SM_CORP_BU_AMT_LC,
    SUM(UE_MP_BUSINESS_CONTRIBUTION_AMT_LC) AS UE_MP_BUSINESS_CONTRIBUTION_AMT_LC,
    SUM(UE_MP_MNG_GNA_CORP_AMT_LC) AS UE_MP_MNG_GNA_CORP_AMT_LC,
    SUM(UE_MP_MNG_SM_CORP_AMT_LC) AS UE_MP_MNG_SM_CORP_AMT_LC,
    SUM(UE_MP_MNG_PD_BM_AMT_LC) AS UE_MP_MNG_PD_BM_AMT_LC,
    SUM(UE_MP_BUSINESS_MARGIN_AMT_LC) AS UE_MP_BUSINESS_MARGIN_AMT_LC,
    SUM(UE_MP_MNG_INTERCO_ADJ_AMT_LC) AS UE_MP_MNG_INTERCO_ADJ_AMT_LC,
    SUM(UE_MP_MNG_PD_ADJ_AMT_LC) AS UE_MP_MNG_PD_ADJ_AMT_LC,
    SUM(UE_MP_OTHER_EBIT_ADJ_AMT_LC) AS UE_MP_OTHER_EBIT_ADJ_AMT_LC,
    SUM(UE_MP_EBIT_AMT_LC) AS UE_MP_EBIT_AMT_LC,
    SUM(UE_MP_MNG_FINANCING_ADJ_AMT_LC) AS UE_MP_MNG_FINANCING_ADJ_AMT_LC,
    SUM(UE_MP_MNG_OTHER_VARIABLE_FINTECH_COSTS_POINT_AMT_LC) AS UE_MP_MNG_OTHER_VARIABLE_FINTECH_COSTS_POINT_AMT_LC,
    SUM(UE_MP_MNG_OWN_CHANNELS_AMT_LC) AS UE_MP_MNG_OWN_CHANNELS_AMT_LC,
    SUM(UE_MP_MNG_POM_ACQUISITION_AMT_LC) AS UE_MP_MNG_POM_ACQUISITION_AMT_LC
  -- no console do BQ precisa do projeto; na ferramenta interna
  -- "WHOWNER.BT_MP_UNIT_ECONOMICS" tambem funciona
  FROM `meli-bi-data.WHOWNER.BT_MP_UNIT_ECONOMICS`
  WHERE UE_DATE BETWEEN UE_DATE_DESDE AND UE_DATE_HASTA
  GROUP BY ALL
),

-- 2) wide -> long (uma linha por campo da UE)
ue_long AS (
  SELECT
    PERIODO,
    SIT_SITE_ID,
    UE_MP_BU_MANAGERIAL,
    UE_MP_SUBBU_MANAGERIAL,
    UE_MP_PRODUCT_MANAGERIAL,
    CAMPO_UE,
    VALOR
  FROM base
  UNPIVOT (VALOR FOR CAMPO_UE IN (
    PROCESSING_FEE_COLLECTOR,
    PROCESSING_FEE_PAYER,
    UE_MP_REVENUE_SHARE_LC,
    UE_MP_SPREAD_MARK_UP_AMT_LC,
    UE_MP_PROCESSING_FEE_MANUAL_AMT_LC,
    UE_MP_NETWORK_FEE_AMT_LC,
    UE_MP_CHG_AMT_LC,
    CARD_INTERCHANGE_FEES,
    CARD_SPREAD,
    CARD_EXTRACTION_FEE,
    UE_MP_LYL_CASHBACK_TD,
    UE_MP_OTH_CARD_REV_AMT_LC,
    UE_MP_CARD_FX_ADJ_AMT_LC,
    INSURTECH_FEE,
    INSURTECH_FEE_PLATAFORMA,
    INSURTECH_FEE_PUBLICIDAD,
    UE_MP_INSUR_DISCOUNT_AMT_LC,
    CRYPTOCURRENCY,
    UE_MP_INVESTMENT_REV_AMT_LC,
    UE_MP_INVESTMENT_REV_MLB_AMT_LC,
    UE_MP_TURBINED_REV_AMT_LC,
    UE_MP_FUNDS_REV_AMT_LC,
    UE_MP_CDB_INVESTMENT_REV_AMT_LC,
    UE_MP_CASHBACKS_CTA_REM_AMT_LC,
    MONEY_IN_FEES_DA,
    MONEY_OUT_FEE_DA,
    CASH_OUT_FEES_DA,
    UE_MP_MNG_OTHER_VAR_FEES_AMT_LC,
    UE_MP_ULTRAPASSE_AMT_LC,
    DISBURSEMENT,
    UE_MP_LYL_CASHBACK,
    UE_MP_OTHER_PRODUCT_COGS_AMT_LC,
    UE_MP_PRODUCT_MONETIZATION_AMT_LC,
    UE_MP_INSUR_PERF_BONUS_FEE_LC,
    UE_MP_INSUR_SIGNING_BONUS_FEE_LC,
    FINANCING_GROSS,
    UE_MP_FINANCING_GROSS_MANUAL_LC,
    UE_MP_FLOATING_AMT_LC,
    UE_MP_BLOCKED_REV_AMT_LC,
    UE_MP_CDB_PROP_INVESTMENT_REV_AMT_LC,
    UE_MP_FINANCING_COST_FTP_AMT_LC,
    UE_MP_COSTO_PLAZO_FTP_AMT_LC,
    SALDOS_BLOQUEADOS_MLB,
    UE_MP_FEE_RIESGO_AMT_LC,
    SALE_TAXES,
    UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC,
    SALE_TAXES_MPOS,
    UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC_MPOS,
    UE_MP_NET_MONETIZATION_AMT_LC,
    COLLECTION_COST,
    INCENTIVE_CUBO,
    CHARGEBACKS,
    UE_MP_CBK_PREVISION_AMT_LC,
    REFUND_SEL,
    REFUND_BUY,
    REFUND_DISPUTE,
    REFUND_THIRD,
    REFUND_VINCULATE,
    UE_MP_MNG_BAD_DEBT_AMT_LC,
    UE_MP_FUNDING_COST_FTP_AMT_LC,
    UE_MP_MNG_BPP_AMT_LC,
    UE_MP_MNG_MKT_PERF_AMT_LC,
    UE_MP_MNG_CX_VAR_AMT_LC,
    UE_MP_MNG_HST_VAR_AMT_LC,
    UE_MP_MNG_FRD_PREV_BURO_AMT_LC,
    MONEY_IN_COST_DA,
    MONEY_OUT_COST_DA,
    CASH_OUT_COST_DA,
    UE_MP_MONEY_OUT_FIXED_COST_AMT_LC,
    UE_MP_CASH_OUT_FIXED_COST_AMT_LC,
    ATM_INQUIRY_FIXED_COST,
    ATM_WITHDRAWAL_FIXED_COST,
    ATM_WITHDRAWAL_PERC_COST_AMT_LC,
    UE_MP_COSTO_ALIAS_AMT_LC,
    UE_MP_TARIFA_INTERBANCARIA_ATM_LC,
    CARD_MASTER_COST,
    CARD_VISA_COST,
    BRAND_COST_TRX,
    BRAND_AUTHORIZATION_FEE,
    BRAND_CLEARING_FEE,
    BRAND_PERC_COST_TRX_AMT_LC,
    BRAND_PERC_COST_NO_TRX_AMT_LC,
    TOKEN_BRAND_PERC_COST_AMT_LC,
    CARD_INCENTIVE_PPD,
    INCENTIVE_TRX_AMT_LC,
    INCENTIVE_PERC_COST_TRX_AMT_LC,
    PRODUCTION_PROCESSING_COST,
    CONDUCTOR_COST,
    PROCESSING_COST_TRX,
    UE_MP_MNG_SVC_CRD_AMT_LC,
    UE_MP_MNG_COMM_RSLR_AMT_LC,
    UE_MP_MNG_OTH_DIR_VAR_COST_AMT_LC,
    UE_MP_MNG_TLM_AMT_LC,
    UE_MP_MNG_DISCOUNT_AMT_LC,
    UE_MP_PAYER_DISCOUNT_AMT_LC,
    UE_MP_INCENTIVES_SELLERS_AMT_LC,
    UE_MP_BONIFICACIONES_SELLERS_AMT_LC,
    UE_MP_CUPONES_SELLER_AMT_LC,
    UE_MP_DISC_CBCK_PAYER_AMT_LC,
    UE_MP_MNG_CERTIFIED_ADVISOR_AMT_LC,
    UE_MP_MNG_COUPONS_AMT_LC,
    UE_MP_VC_PRICING_AMT_LC,
    UE_MP_DC_PRICING_AMT_LC,
    UE_MP_VARIABLE_CONTRIBUTION_EXC_FIN_ADJ_AMT_LC,
    UE_MP_VARIABLE_CONTRIBUTION_AMT_LC,
    UE_MP_VARIABLE_CONTRIBUTION_ADJ_AMT_LC,
    MPOS_SALE,
    UE_MP_ALQUILER_MPOS_AMT_LC,
    MPOS_DISCOUNT,
    UE_MP_MNG_BAD_DEBIT_POINT_AMT_LC,
    UE_MP_MNG_COST_PRD_SOLD_AMT_LC,
    UE_MP_MNG_SHP_COST_POINT_AMT_LC,
    UE_MP_MNG_WHS_COST_POINT_AMT_LC,
    UE_MP_MNG_SUPP_COST_POINT_AMT_LC,
    UE_MP_MNG_RECOND_AMT_LC,
    UE_MP_MNG_OTH_MPOS_COGS_AMT_LC,
    UE_MP_MNG_PREV_COST_MPOS_AMT_LC,
    UE_MP_MNG_POM_POINT_AMT_LC,
    UE_MP_MKT_POM_SELLERS_AMT_LC,
    UE_MP_MKT_POM_ACTIVATION_AMT_LC,
    UE_MP_MKT_POM_ADQUISITION_AMT_LC,
    UE_MP_MNG_COMISIONES_RESELLERS_POINT_AMT_LC,
    UE_MP_MNG_SLS_FORCE_MPOS_AMT_LC,
    UE_MP_MNG_SLS_FORCE_AMT_LC,
    UE_MP_MNG_SLS_FORCE_PROPIA_AMT_LC,
    UE_MP_MNG_OTHER_SALES_EXPENSES_POINT_AMT_LC,
    UE_MP_MNG_TELEVENTAS_AMT_LC,
    UE_MP_MNG_WEB_TERC_AMT_LC,
    UE_MP_MNG_PRES_LCL_AMT_LC,
    UE_MP_MNG_MGM_AMT_LC,
    MONTO_EMISION_COST,
    MONTO_SHIPPING_COST,
    UE_MP_CARD_REPRINT_FEES_AMT_LC,
    UE_MP_MNG_OTH_FIX_COST_AMT_LC,
    UE_MP_MNG_OTHER_FIXED_FINTECH_COSTS_AMT_LC,
    UE_MP_MNG_INI_AMT_LC,
    UE_MP_MNG_SPEC_DATE_AMT_LC,
    UE_MP_MNG_OTH_MKT_EXP_AMT_LC,
    UE_MP_MNG_MKT_INVEST_ADJ_AMT_LC,
    UE_MP_MNG_OTH_SLS_EXP_AMT_LC,
    UE_MP_MNG_LY_CNT_SUBX_REVS_AMT_LC,
    UE_MP_MNG_LY_CNT_ORG_AMT_LC,
    UE_MP_MNG_LY_CNT_SUBS_COST_AMT_LC,
    UE_MP_MNG_CX_FIX_AMT_LC,
    UE_MP_MNG_HST_FIX_AMT_LC,
    UE_MP_MNG_FRD_PREV_AMT_LC,
    UE_MP_MNG_SM_LC_AMT_LC,
    UE_MP_SHIPPING_OPS_FIXED_AMT_LC,
    UE_MP_DC_AMT_LC,
    UE_MP_MNG_MKT_BRAND_AMT_LC,
    UE_MP_MNG_PD_DIR_AMT_LC,
    UE_MP_MNG_PD_INDIR_AMT_LC,
    UE_MP_MNG_GNA_LC_AMT_LC,
    UE_MP_MNG_GNA_CORP_SUBBU_AMT_LC,
    UE_MP_MNG_GNA_CORP_BU_AMT_LC,
    UE_MP_MNG_SM_CORP_SUBBU_AMT_LC,
    UE_MP_MNG_SM_CORP_BU_AMT_LC,
    UE_MP_BUSINESS_CONTRIBUTION_AMT_LC,
    UE_MP_MNG_GNA_CORP_AMT_LC,
    UE_MP_MNG_SM_CORP_AMT_LC,
    UE_MP_MNG_PD_BM_AMT_LC,
    UE_MP_BUSINESS_MARGIN_AMT_LC,
    UE_MP_MNG_INTERCO_ADJ_AMT_LC,
    UE_MP_MNG_PD_ADJ_AMT_LC,
    UE_MP_OTHER_EBIT_ADJ_AMT_LC,
    UE_MP_EBIT_AMT_LC,
    UE_MP_MNG_FINANCING_ADJ_AMT_LC,
    UE_MP_MNG_OTHER_VARIABLE_FINTECH_COSTS_POINT_AMT_LC,
    UE_MP_MNG_OWN_CHANNELS_AMT_LC,
    UE_MP_MNG_POM_ACQUISITION_AMT_LC
  ))
),

-- 3) de/para CAMPO_UE -> linha do PYL (fonte da verdade do mapping)
mapa AS (
  SELECT * FROM UNNEST(ARRAY<STRUCT<
      CAMPO_UE    STRING,
      NUMERACION  STRING,
      NOMBRE_PYL  STRING,
      NIVEL_PNL   STRING,
      N1_MARGEN   STRING,
      N2_SUBTOTAL STRING,
      N3_DETALLE  STRING,
      N4_UE       STRING,
      TIPO_LINEA  STRING,
      SUGERENCIA  STRING
  >>[
    ('PROCESSING_FEE_COLLECTOR', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('PROCESSING_FEE_PAYER', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('UE_MP_REVENUE_SHARE_LC', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('UE_MP_SPREAD_MARK_UP_AMT_LC', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('UE_MP_PROCESSING_FEE_MANUAL_AMT_LC', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('UE_MP_NETWORK_FEE_AMT_LC', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('UE_MP_CHG_AMT_LC', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('UE_MP_DISC_CBCK_PAYER_AMT_LC', 'A.1.1', 'Processing Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.1 Processing Fees', NULL, 'PYL', NULL),
    ('CARD_INTERCHANGE_FEES', 'A.1.2.1', 'Interchange Fee', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.2 Card Fees', 'A.1.2.1 Interchange Fee', 'PYL', NULL),
    ('CARD_SPREAD', 'A.1.2.2', 'Spread', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.2 Card Fees', 'A.1.2.2 Spread', 'PYL', NULL),
    ('CARD_EXTRACTION_FEE', 'A.1.2.3', 'Extracciones', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.2 Card Fees', 'A.1.2.3 Extracciones', 'PYL', NULL),
    ('UE_MP_LYL_CASHBACK_TD', 'A.1.2.4', 'Other Card Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.2 Card Fees', 'A.1.2.4 Other Card Revenues', 'PYL', NULL),
    ('UE_MP_OTH_CARD_REV_AMT_LC', 'A.1.2.4', 'Other Card Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.2 Card Fees', 'A.1.2.4 Other Card Revenues', 'PYL', NULL),
    ('UE_MP_CARD_FX_ADJ_AMT_LC', 'A.1.2.5', 'Ajuste FX - Card', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.2 Card Fees', 'A.1.2.5 Ajuste FX - Card', 'PYL', NULL),
    ('INSURTECH_FEE', 'A.1.3.1', 'Insurtech Fees', 'PYL_3_VARCHAR', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.3 Insurtech Variable Fees', 'A.1.3.1 Insurtech Fees', 'PYL', NULL),
    ('UE_MP_INSUR_DISCOUNT_AMT_LC', 'A.1.3.1', 'Insurtech Fees', 'PYL_3_VARCHAR', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.3 Insurtech Variable Fees', 'A.1.3.1 Insurtech Fees', 'PYL', NULL),
    ('INSURTECH_FEE_PUBLICIDAD', 'A.1.3.2', 'Publicidad Insurtech', 'PYL_4_VARCHAR', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.3 Insurtech Variable Fees', 'A.1.3.2 Publicidad Insurtech', 'PYL', NULL),
    ('INSURTECH_FEE_PLATAFORMA', 'A.1.3.3', 'Uso de Plataforma Insurtech', 'PYL_4_VARCHAR', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.3 Insurtech Variable Fees', 'A.1.3.3 Uso de Plataforma Insurtech', 'PYL', NULL),
    ('CRYPTOCURRENCY', 'A.1.4.1', 'Crypto Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.4 Investment Revenues', 'A.1.4.1 Crypto Revenues', 'PYL', NULL),
    ('UE_MP_INVESTMENT_REV_AMT_LC', 'A.1.4.2', 'Investment Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.4 Investment Revenues', 'A.1.4.2 Investment Revenues', 'PYL', NULL),
    ('UE_MP_INVESTMENT_REV_MLB_AMT_LC', 'A.1.4.2', 'Investment Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.4 Investment Revenues', 'A.1.4.2 Investment Revenues', 'PYL', NULL),
    ('UE_MP_TURBINED_REV_AMT_LC', 'A.1.4.2', 'Investment Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.4 Investment Revenues', 'A.1.4.2 Investment Revenues', 'PYL', NULL),
    ('UE_MP_FUNDS_REV_AMT_LC', 'A.1.4.2', 'Investment Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.4 Investment Revenues', 'A.1.4.2 Investment Revenues', 'PYL', NULL),
    ('UE_MP_CDB_INVESTMENT_REV_AMT_LC', 'A.1.4.2', 'Investment Revenues', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.4 Investment Revenues', 'A.1.4.2 Investment Revenues', 'PYL', NULL),
    ('UE_MP_CASHBACKS_CTA_REM_AMT_LC', 'A.1.4.3', 'Menor Revenue Asset Mgmt', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.4 Investment Revenues', 'A.1.4.3 Menor Revenue Asset Mgmt', 'PYL', NULL),
    ('MONEY_IN_FEES_DA', 'A.1.5.1', 'Money In Fees', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.5 Other Variable Fees', 'A.1.5.1 Money In Fees', 'PYL', NULL),
    ('MONEY_OUT_FEE_DA', 'A.1.5.2', 'Money Out Fees', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.5 Other Variable Fees', 'A.1.5.2 Money Out Fees', 'PYL', NULL),
    ('CASH_OUT_FEES_DA', 'A.1.5.3', 'Cash Out Fees', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.5 Other Variable Fees', 'A.1.5.3 Cash Out Fees', 'PYL', NULL),
    ('UE_MP_MNG_OTHER_VAR_FEES_AMT_LC', 'A.1.5.4', 'Other Variable Fees', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.5 Other Variable Fees', 'A.1.5.4 Other Variable Fees', 'PYL', NULL),
    ('UE_MP_ULTRAPASSE_AMT_LC', 'A.1.5.4', 'Other Variable Fees', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.5 Other Variable Fees', 'A.1.5.4 Other Variable Fees', 'PYL', NULL),
    ('DISBURSEMENT', 'A.1.5.4', 'Other Variable Fees', 'PYL_MANAGERIAL_UE_NEW', 'A. Product Monetization', 'A.1 Net Variable Fees', 'A.1.5 Other Variable Fees', 'A.1.5.4 Other Variable Fees', 'PYL', NULL),
    ('UE_MP_INSUR_PERF_BONUS_FEE_LC', 'A.2.1', 'Insurtech Fixed Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.2 Net Fixed Fees', 'A.2.1 Insurtech Fixed Fees', NULL, 'PYL', NULL),
    ('UE_MP_INSUR_SIGNING_BONUS_FEE_LC', 'A.2.1', 'Insurtech Fixed Fees', 'PYL_DETAIL_MANAGERIAL_NEW', 'A. Product Monetization', 'A.2 Net Fixed Fees', 'A.2.1 Insurtech Fixed Fees', NULL, 'PYL', NULL),
    ('UE_MP_LYL_CASHBACK', 'A.3', 'Promotions', 'SUBTOTALES_MANAGERIAL_NEW', 'A. Product Monetization', 'A.3 Promotions', NULL, NULL, 'PYL', NULL),
    ('UE_MP_OTHER_PRODUCT_COGS_AMT_LC', 'A.4', 'Other Product Cogs', 'SUBTOTALES_MANAGERIAL_NEW', 'A. Product Monetization', 'A.4 Other Product Cogs', NULL, NULL, 'PYL', NULL),
    ('FINANCING_GROSS', 'B.5.1.1', 'Financing Gross', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.1 Financing Revenues', 'B.5.1.1 Financing Gross', 'PYL', NULL),
    ('UE_MP_FINANCING_GROSS_MANUAL_LC', 'B.5.1.1', 'Financing Gross', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.1 Financing Revenues', 'B.5.1.1 Financing Gross', 'PYL', NULL),
    ('UE_MP_FLOATING_AMT_LC', 'B.5.1.2', 'Floating Revenues', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.1 Financing Revenues', 'B.5.1.2 Floating Revenues', 'PYL', NULL),
    ('UE_MP_BLOCKED_REV_AMT_LC', 'B.5.1.3', 'Interest income on restricted balance', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.1 Financing Revenues', 'B.5.1.3 Interest income on restricted balance', 'PYL', NULL),
    ('SALDOS_BLOQUEADOS_MLB', 'B.5.1.3', 'Interest income on restricted balance', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.1 Financing Revenues', 'B.5.1.3 Interest income on restricted balance', 'PYL', NULL),
    ('UE_MP_FINANCING_COST_FTP_AMT_LC', 'B.5.2.1', 'Theoretical financing cost', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.2 Financing Costs', 'B.5.2.1 Theoretical financing cost', 'PYL', NULL),
    ('UE_MP_COSTO_PLAZO_FTP_AMT_LC', 'B.5.2.2', 'Holding Interest Income', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.2 Financing Costs', 'B.5.2.2 Holding Interest Income', 'PYL', NULL),
    ('UE_MP_FEE_RIESGO_AMT_LC', 'B.5.2.3', 'Financing Cost Fee de Riesgo', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.2 Financing Costs', 'B.5.2.3 Financing Cost Fee de Riesgo', 'PYL', NULL),
    ('UE_MP_CDB_PROP_INVESTMENT_REV_AMT_LC', 'B.5.2.4', 'Financing Cost CDB', 'PYL_MANAGERIAL_UE_NEW', 'B. Net Monetization', 'B.5 Financing Net', 'B.5.2 Financing Costs', 'B.5.2.4 Financing Cost CDB', 'PYL', NULL),
    ('SALE_TAXES', 'B.6', 'Sales Taxes', 'SUBTOTALES_MANAGERIAL_NEW', 'B. Net Monetization', 'B.6 Sales Taxes', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC', 'B.6', 'Sales Taxes', 'SUBTOTALES_MANAGERIAL_NEW', 'B. Net Monetization', 'B.6 Sales Taxes', NULL, NULL, 'PYL', NULL),
    ('COLLECTION_COST', 'C.8', 'Collection Fees', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.8 Collection Fees', NULL, NULL, 'PYL', NULL),
    ('INCENTIVE_CUBO', 'C.8', 'Collection Fees', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.8 Collection Fees', NULL, NULL, 'PYL', NULL),
    ('CHARGEBACKS', 'C.9.1', 'Chargebacks gross', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.9 Chargebacks', 'C.9.1 Chargebacks gross', NULL, 'PYL', NULL),
    ('REFUND_SEL', 'C.9.2', 'Chargebacks recoveries', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.9 Chargebacks', 'C.9.2 Chargebacks recoveries', NULL, 'PYL', NULL),
    ('REFUND_BUY', 'C.9.2', 'Chargebacks recoveries', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.9 Chargebacks', 'C.9.2 Chargebacks recoveries', NULL, 'PYL', NULL),
    ('REFUND_DISPUTE', 'C.9.2', 'Chargebacks recoveries', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.9 Chargebacks', 'C.9.2 Chargebacks recoveries', NULL, 'PYL', NULL),
    ('REFUND_THIRD', 'C.9.2', 'Chargebacks recoveries', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.9 Chargebacks', 'C.9.2 Chargebacks recoveries', NULL, 'PYL', NULL),
    ('REFUND_VINCULATE', 'C.9.2', 'Chargebacks recoveries', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.9 Chargebacks', 'C.9.2 Chargebacks recoveries', NULL, 'PYL', NULL),
    ('UE_MP_CBK_PREVISION_AMT_LC', 'C.9.3', 'Ajuste contable cbk', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.9 Chargebacks', 'C.9.3 Ajuste contable cbk', NULL, 'PYL', 'NIVEL_PNL vazio no mapping original - assumido PYL_DETAIL_MANAGERIAL_NEW'),
    ('UE_MP_MNG_BAD_DEBT_AMT_LC', 'C.10', 'Bad Debt', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.10 Bad Debt', NULL, NULL, 'PYL', NULL),
    ('UE_MP_FUNDING_COST_FTP_AMT_LC', 'C.11', 'Funding', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.11 Funding', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_BPP_AMT_LC', 'C.12', 'BPP', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.12 BPP', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_CX_VAR_AMT_LC', 'C.14', 'CX Variable', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.14 CX Variable', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_HST_VAR_AMT_LC', 'C.15', 'Hosting Variable', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.15 Hosting Variable', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_FRD_PREV_BURO_AMT_LC', 'C.16', 'Fraud Prevention Variable', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.16 Fraud Prevention Variable', NULL, NULL, 'PYL', NULL),
    ('MONEY_IN_COST_DA', 'C.17.1', 'Money In costs', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.1 Money In costs', NULL, 'PYL', NULL),
    ('MONEY_OUT_COST_DA', 'C.17.2', 'Money Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.2 Money Out', NULL, 'PYL', NULL),
    ('UE_MP_MONEY_OUT_FIXED_COST_AMT_LC', 'C.17.2', 'Money Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.2 Money Out', NULL, 'PYL', NULL),
    ('UE_MP_COSTO_ALIAS_AMT_LC', 'C.17.2', 'Money Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.2 Money Out', NULL, 'PYL', NULL),
    ('UE_MP_TARIFA_INTERBANCARIA_ATM_LC', 'C.17.2', 'Money Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.2 Money Out', NULL, 'PYL', NULL),
    ('CASH_OUT_COST_DA', 'C.17.3', 'Cash Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.3 Cash Out', NULL, 'PYL', NULL),
    ('UE_MP_CASH_OUT_FIXED_COST_AMT_LC', 'C.17.3', 'Cash Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.3 Cash Out', NULL, 'PYL', NULL),
    ('ATM_INQUIRY_FIXED_COST', 'C.17.3', 'Cash Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.3 Cash Out', NULL, 'PYL', NULL),
    ('ATM_WITHDRAWAL_FIXED_COST', 'C.17.3', 'Cash Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.3 Cash Out', NULL, 'PYL', NULL),
    ('ATM_WITHDRAWAL_PERC_COST_AMT_LC', 'C.17.3', 'Cash Out', 'PYL_3_VARCHAR', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.3 Cash Out', NULL, 'PYL', NULL),
    ('CARD_MASTER_COST', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('CARD_VISA_COST', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('BRAND_COST_TRX', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('BRAND_AUTHORIZATION_FEE', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('BRAND_CLEARING_FEE', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('BRAND_PERC_COST_TRX_AMT_LC', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('BRAND_PERC_COST_NO_TRX_AMT_LC', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('TOKEN_BRAND_PERC_COST_AMT_LC', 'C.17.4.1', 'Costos banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.1 Costos banderas', 'PYL', NULL),
    ('CARD_INCENTIVE_PPD', 'C.17.4.2', 'Incentivos Banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.2 Incentivos Banderas', 'PYL', NULL),
    ('INCENTIVE_TRX_AMT_LC', 'C.17.4.2', 'Incentivos Banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.2 Incentivos Banderas', 'PYL', NULL),
    ('INCENTIVE_PERC_COST_TRX_AMT_LC', 'C.17.4.2', 'Incentivos Banderas', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.2 Incentivos Banderas', 'PYL', NULL),
    ('PRODUCTION_PROCESSING_COST', 'C.17.4.3', 'Costos procesamiento', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.3 Costos procesamiento', 'PYL', NULL),
    ('CONDUCTOR_COST', 'C.17.4.3', 'Costos procesamiento', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.3 Costos procesamiento', 'PYL', NULL),
    ('PROCESSING_COST_TRX', 'C.17.4.3', 'Costos procesamiento', 'PYL_MANAGERIAL_UE_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.4 Card Variable Costs', 'C.17.4.3 Costos procesamiento', 'PYL', NULL),
    ('UE_MP_MNG_COMM_RSLR_AMT_LC', 'C.17.5', 'Comisiones resellers', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.5 Comisiones resellers', NULL, 'PYL', NULL),
    ('UE_MP_MNG_OTH_DIR_VAR_COST_AMT_LC', 'C.17.6', 'Other Variable Fintech Costs', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.6 Other Variable Fintech Costs', NULL, 'PYL', NULL),
    ('UE_MP_MNG_OTHER_VARIABLE_FINTECH_COSTS_POINT_AMT_LC', 'C.17.6', 'Other Variable Fintech Costs', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.6 Other Variable Fintech Costs', NULL, 'PYL', NULL),
    ('UE_MP_MNG_CERTIFIED_ADVISOR_AMT_LC', 'C.17.6', 'Other Variable Fintech Costs', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.6 Other Variable Fintech Costs', NULL, 'PYL', NULL),
    ('UE_MP_MNG_TLM_AMT_LC', 'C.17.7', 'Telemetria', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.7 Telemetria', NULL, 'PYL', NULL),
    ('UE_MP_MNG_DISCOUNT_AMT_LC', 'C.17.8', 'Descuentos', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.8 Descuentos', NULL, 'PYL', NULL),
    ('UE_MP_PAYER_DISCOUNT_AMT_LC', 'C.17.8', 'Descuentos', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.8 Descuentos', NULL, 'PYL', NULL),
    ('UE_MP_INCENTIVES_SELLERS_AMT_LC', 'C.17.8', 'Descuentos', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.8 Descuentos', NULL, 'PYL', NULL),
    ('UE_MP_BONIFICACIONES_SELLERS_AMT_LC', 'C.17.8', 'Descuentos', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.8 Descuentos', NULL, 'PYL', NULL),
    ('UE_MP_CUPONES_SELLER_AMT_LC', 'C.17.8', 'Descuentos', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.8 Descuentos', NULL, 'PYL', NULL),
    ('UE_MP_MNG_SVC_CRD_AMT_LC', 'C.17.9', 'Servicios de Cobranzas Credits', 'PYL_DETAIL_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.17 Direct Variable Costs', 'C.17.9 Servicios de Cobranzas Credits', NULL, 'PYL', NULL),
    ('UE_MP_MNG_MKT_PERF_AMT_LC', 'C.18', 'Marketing Performance', 'SUBTOTALES_MANAGERIAL_NEW', 'C. Variable Contribution', 'C.18 Marketing Performance', NULL, NULL, 'PYL', NULL),
    ('MPOS_SALE', 'D.19.1.1', 'Sales MPOS Gross', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.1 Sales MPOS', 'D.19.1.1 Sales MPOS Gross', 'PYL', NULL),
    ('UE_MP_MNG_BAD_DEBIT_POINT_AMT_LC', 'D.19.1.2', 'Bad Debt MPOS', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.1 Sales MPOS', 'D.19.1.2 Bad Debt MPOS', 'PYL', NULL),
    ('MPOS_DISCOUNT', 'D.19.1.3', 'Descuentos MPOS', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.1 Sales MPOS', 'D.19.1.3 Descuentos MPOS', 'PYL', NULL),
    ('SALE_TAXES_MPOS', 'D.19.1.4', 'Sales tax MPOS', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.1 Sales MPOS', 'D.19.1.4 Sales tax MPOS', 'PYL', NULL),
    ('UE_MP_MNG_SALES_TAXES_ADJ_AMT_LC_MPOS', 'D.19.1.4', 'Sales tax MPOS', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.1 Sales MPOS', 'D.19.1.4 Sales tax MPOS', 'PYL', NULL),
    ('UE_MP_ALQUILER_MPOS_AMT_LC', 'D.19.1.5', 'Alquiler MPOS', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.1 Sales MPOS', 'D.19.1.5 Alquiler MPOS', 'PYL', NULL),
    ('UE_MP_MNG_COST_PRD_SOLD_AMT_LC', 'D.19.2.1', 'Cost of Product Sold', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.2 Point COGS', 'D.19.2.1 Cost of Product Sold', 'PYL', NULL),
    ('UE_MP_MNG_SHP_COST_POINT_AMT_LC', 'D.19.2.2', 'Shipping Costs Point', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.2 Point COGS', 'D.19.2.2 Shipping Costs Point', 'PYL', NULL),
    ('UE_MP_MNG_WHS_COST_POINT_AMT_LC', 'D.19.2.3', 'Warehousing Point', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.2 Point COGS', 'D.19.2.3 Warehousing Point', 'PYL', NULL),
    ('UE_MP_MNG_SUPP_COST_POINT_AMT_LC', 'D.19.2.4', 'Insumos Point', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.2 Point COGS', 'D.19.2.4 Insumos Point', 'PYL', NULL),
    ('UE_MP_MNG_RECOND_AMT_LC', 'D.19.2.5', 'Reacondicionamiento', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.2 Point COGS', 'D.19.2.5 Reacondicionamiento', 'PYL', NULL),
    ('UE_MP_MNG_OTH_MPOS_COGS_AMT_LC', 'D.19.2.6', 'Other MPOS Cogs', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.2 Point COGS', 'D.19.2.6 Other MPOS Cogs', 'PYL', NULL),
    ('UE_MP_MNG_PREV_COST_MPOS_AMT_LC', 'D.19.3', 'Prevision MPOS Cost', 'PYL_DETAIL_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.3 Prevision MPOS Cost', NULL, 'PYL', NULL),
    ('UE_MP_MNG_COMISIONES_RESELLERS_POINT_AMT_LC', 'D.19.4.1', 'Comisiones a Resellers Point', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.1 Comisiones a Resellers Point', 'PYL', NULL),
    ('UE_MP_MNG_SLS_FORCE_MPOS_AMT_LC', 'D.19.4.2', 'Fuerza de Venta de Terceros Point', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.2 Fuerza de Venta de Terceros Point', 'PYL', NULL),
    ('UE_MP_MNG_SLS_FORCE_PROPIA_AMT_LC', 'D.19.4.3', 'Fuerza de Venta Propia Acquiring', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.3 Fuerza de Venta Propia Acquiring', 'PYL', NULL),
    ('UE_MP_MNG_OTHER_SALES_EXPENSES_POINT_AMT_LC', 'D.19.4.4', 'Other Sales Expenses Point', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.4 Other Sales Expenses Point', 'PYL', NULL),
    ('UE_MP_MNG_TELEVENTAS_AMT_LC', 'D.19.4.5', 'Televentas', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.5 Televentas', 'PYL', NULL),
    ('UE_MP_MNG_WEB_TERC_AMT_LC', 'D.19.4.6', 'Venta en pagina web de terceros', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.6 Venta en pagina web de terceros', 'PYL', NULL),
    ('UE_MP_MNG_PRES_LCL_AMT_LC', 'D.19.4.7', 'Venta presencial en locales', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.7 Venta presencial en locales', 'PYL', NULL),
    ('UE_MP_MNG_MGM_AMT_LC', 'D.19.4.8', 'MGM', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.19 Customer Acquisition Cost', 'D.19.4 CPA', 'D.19.4.8 MGM', 'PYL', NULL),
    ('MONTO_EMISION_COST', 'D.20.1.1', 'Issuing Costs', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.20 Other Fixed Costs', 'D.20.1 Card Fixed Net', 'D.20.1.1 Issuing Costs', 'PYL', NULL),
    ('MONTO_SHIPPING_COST', 'D.20.1.2', 'Shipping Distribution', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.20 Other Fixed Costs', 'D.20.1 Card Fixed Net', 'D.20.1.2 Shipping Distribution', 'PYL', NULL),
    ('UE_MP_CARD_REPRINT_FEES_AMT_LC', 'D.20.1.3', 'Cards reprint', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.20 Other Fixed Costs', 'D.20.1 Card Fixed Net', 'D.20.1.3 Cards reprint', 'PYL', NULL),
    ('UE_MP_MNG_OTH_FIX_COST_AMT_LC', 'D.20.2', 'Other Fixed Costs', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.20 Other Fixed Costs', 'D.20.2 Other Fixed Costs', NULL, 'PYL', NULL),
    ('UE_MP_MNG_OTHER_FIXED_FINTECH_COSTS_AMT_LC', 'D.20.3', 'Other Fixed Fintech Costs', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.20 Other Fixed Costs', 'D.20.3 Other Fixed Fintech Costs', NULL, 'PYL', NULL),
    ('UE_MP_MNG_OTH_SLS_EXP_AMT_LC', 'D.22.1', 'Other Sales Expenses DC', 'PYL_DETAIL_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.22 Sales Expenses', 'D.22.1 Other Sales Expenses DC', NULL, 'PYL', NULL),
    ('UE_MP_MNG_SLS_FORCE_AMT_LC', 'D.22.2', 'Fuerza de Ventas', 'PYL_DETAIL_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.22 Sales Expenses', 'D.22.2 Fuerza de Ventas', NULL, 'PYL', NULL),
    ('UE_MP_MNG_LY_CNT_SUBX_REVS_AMT_LC', 'D.23', 'Loyalty Content', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.23 Loyalty Content', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_LY_CNT_ORG_AMT_LC', 'D.23', 'Loyalty Content', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.23 Loyalty Content', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_LY_CNT_SUBS_COST_AMT_LC', 'D.23', 'Loyalty Content', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.23 Loyalty Content', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_CX_FIX_AMT_LC', 'D.24', 'CX Fixed', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.24 CX Fixed', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_HST_FIX_AMT_LC', 'D.25', 'Hosting Fixed', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.25 Hosting Fixed', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_FRD_PREV_AMT_LC', 'D.26', 'Fraud Prevention Fixed', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.26 Fraud Prevention Fixed', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_SM_LC_AMT_LC', 'D.27', 'S&M Local DC', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.27 S&M Local DC', NULL, NULL, 'PYL', NULL),
    ('UE_MP_SHIPPING_OPS_FIXED_AMT_LC', 'D.28', 'Shipping Ops Fixed', 'SUBTOTALES_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.28 Shipping Ops Fixed', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_OWN_CHANNELS_AMT_LC', 'D.29.1.1', 'Own Channels - Acquisition', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.1 Customer /Seller Acquisition Cost', 'D.29.1.1 Own Channels - Acquisition', 'PYL', NULL),
    ('UE_MP_MNG_POM_ACQUISITION_AMT_LC', 'D.29.1.2', 'POM Acquisition', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.1 Customer /Seller Acquisition Cost', 'D.29.1.2 POM Acquisition', 'PYL', NULL),
    ('UE_MP_MKT_POM_SELLERS_AMT_LC', 'D.29.1.2', 'POM Acquisition', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.1 Customer /Seller Acquisition Cost', 'D.29.1.2 POM Acquisition', 'PYL', NULL),
    ('UE_MP_MKT_POM_ACTIVATION_AMT_LC', 'D.29.1.2', 'POM Acquisition', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.1 Customer /Seller Acquisition Cost', 'D.29.1.2 POM Acquisition', 'PYL', NULL),
    ('UE_MP_MKT_POM_ADQUISITION_AMT_LC', 'D.29.1.2', 'POM Acquisition', 'PYL_MANAGERIAL_UE_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.1 Customer /Seller Acquisition Cost', 'D.29.1.2 POM Acquisition', 'PYL', NULL),
    ('UE_MP_MNG_SPEC_DATE_AMT_LC', 'D.29.2', 'Demand Generation', 'PYL_DETAIL_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.2 Demand Generation', NULL, 'PYL', NULL),
    ('UE_MP_MNG_MKT_BRAND_AMT_LC', 'D.29.3', 'Marketing Branding', 'PYL_DETAIL_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.3 Marketing Branding', NULL, 'PYL', NULL),
    ('UE_MP_MNG_OTH_MKT_EXP_AMT_LC', 'D.29.4', 'Other Marketing Expenses', 'PYL_DETAIL_MANAGERIAL_NEW', 'D. Direct Contribution', 'D.29 Demand Gen, Branding & Others', 'D.29.4 Other Marketing Expenses', NULL, 'PYL', NULL),
    ('UE_MP_MNG_PD_INDIR_AMT_LC', 'E.29.1', 'PD Directo Corp', 'PYL_DETAIL_MANAGERIAL_NEW', 'E. Business Contribution', 'E.29 PD BC', 'E.29.1 PD Directo Corp', NULL, 'PYL', NULL),
    ('UE_MP_MNG_PD_DIR_AMT_LC', 'E.29.2', 'PD Directo Local', 'PYL_DETAIL_MANAGERIAL_NEW', 'E. Business Contribution', 'E.29 PD BC', 'E.29.2 PD Directo Local', NULL, 'PYL', NULL),
    ('UE_MP_MNG_GNA_CORP_SUBBU_AMT_LC', 'E.30.1', 'G&A Directo Corp', 'PYL_DETAIL_MANAGERIAL_NEW', 'E. Business Contribution', 'E.30 G&A BC', 'E.30.1 G&A Directo Corp', NULL, 'PYL', NULL),
    ('UE_MP_MNG_GNA_LC_AMT_LC', 'E.30.2', 'G&A Directo Local', 'PYL_DETAIL_MANAGERIAL_NEW', 'E. Business Contribution', 'E.30 G&A BC', 'E.30.2 G&A Directo Local', NULL, 'PYL', NULL),
    ('UE_MP_MNG_SM_CORP_SUBBU_AMT_LC', 'E.31', 'S&M BC', 'SUBTOTALES_MANAGERIAL_NEW', 'E. Business Contribution', 'E.31 S&M BC', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_PD_BM_AMT_LC', 'F.33', 'PD BM', 'SUBTOTALES_MANAGERIAL_NEW', 'F. Business Margin', 'F.33 PD BM', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_SM_CORP_AMT_LC', 'F.34', 'S&M BM', 'SUBTOTALES_MANAGERIAL_NEW', 'F. Business Margin', 'F.34 S&M BM', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_GNA_CORP_AMT_LC', 'F.35', 'G&A BM', 'SUBTOTALES_MANAGERIAL_NEW', 'F. Business Margin', 'F.35 G&A BM', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_INTERCO_ADJ_AMT_LC', 'H.39', 'Interco adjustments', 'SUBTOTALES_MANAGERIAL_NEW', 'H. EBIT', 'H.39 Interco adjustments', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_PD_ADJ_AMT_LC', 'H.40', 'PD by site adjustment', 'SUBTOTALES_MANAGERIAL_NEW', 'H. EBIT', 'H.40 PD by site adjustment', NULL, NULL, 'PYL', NULL),
    ('UE_MP_OTHER_EBIT_ADJ_AMT_LC', 'H.43', 'Other EBIT adjustments', 'SUBTOTALES_MANAGERIAL_NEW', 'H. EBIT', 'H.43 Other EBIT adjustments', NULL, NULL, 'PYL', NULL),
    ('UE_MP_MNG_FINANCING_ADJ_AMT_LC', 'H.45', 'FTP Adjustments', 'SUBTOTALES_MANAGERIAL_NEW', 'H. EBIT', 'H.45 FTP Adjustments', NULL, NULL, 'PYL', NULL),
    ('UE_MP_PRODUCT_MONETIZATION_AMT_LC', 'A.', 'Product Monetization (control UE)', 'MARGEN_MANAGERIAL_NEW', 'A. Product Monetization', 'A. Product Monetization (control)', NULL, NULL, 'CONTROL_UE', 'Margem pronta da UE - usar para conciliar, nao somar junto das linhas PYL'),
    ('UE_MP_NET_MONETIZATION_AMT_LC', 'B.', 'Net Monetization (control UE)', 'MARGEN_MANAGERIAL_NEW', 'B. Net Monetization', 'B. Net Monetization (control)', NULL, NULL, 'CONTROL_UE', 'Margem pronta da UE - usar para conciliar'),
    ('UE_MP_VARIABLE_CONTRIBUTION_AMT_LC', 'C.', 'Variable Contribution (control UE)', 'MARGEN_MANAGERIAL_NEW', 'C. Variable Contribution', 'C. Variable Contribution (control)', NULL, NULL, 'CONTROL_UE', 'Margem pronta da UE - usar para conciliar'),
    ('UE_MP_VARIABLE_CONTRIBUTION_EXC_FIN_ADJ_AMT_LC', 'C.*', 'Variable Contribution exc fin adj (control UE)', 'MARGEN_MANAGERIAL_NEW', 'C. Variable Contribution', 'C. Variable Contribution (control)', NULL, NULL, 'CONTROL_UE', 'Variante da margem VC sem ajuste de financiamento'),
    ('UE_MP_DC_AMT_LC', 'D.', 'Direct Contribution (control UE)', 'MARGEN_MANAGERIAL_NEW', 'D. Direct Contribution', 'D. Direct Contribution (control)', NULL, NULL, 'CONTROL_UE', 'Margem pronta da UE - usar para conciliar'),
    ('UE_MP_BUSINESS_CONTRIBUTION_AMT_LC', 'E.', 'Business Contribution (control UE)', 'MARGEN_MANAGERIAL_NEW', 'E. Business Contribution', 'E. Business Contribution (control)', NULL, NULL, 'CONTROL_UE', 'Margem pronta da UE - usar para conciliar'),
    ('UE_MP_BUSINESS_MARGIN_AMT_LC', 'F.', 'Business Margin (control UE)', 'MARGEN_MANAGERIAL_NEW', 'F. Business Margin', 'F. Business Margin (control)', NULL, NULL, 'CONTROL_UE', 'Margem pronta da UE - usar para conciliar'),
    ('UE_MP_EBIT_AMT_LC', 'H.', 'EBIT (control UE)', 'MARGEN_MANAGERIAL_NEW', 'H. EBIT', 'H. EBIT (control)', NULL, NULL, 'CONTROL_UE', 'Margem pronta da UE - usar para conciliar'),
    ('UE_MP_MNG_COUPONS_AMT_LC', 'Z.99.01', 'A categorizar - Coupons', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: C.17.8 Descuentos'),
    ('UE_MP_VC_PRICING_AMT_LC', 'Z.99.02', 'A categorizar - VC Pricing', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: ajuste de pricing dentro de C. Variable Contribution'),
    ('UE_MP_DC_PRICING_AMT_LC', 'Z.99.03', 'A categorizar - DC Pricing', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: ajuste de pricing dentro de D. Direct Contribution'),
    ('UE_MP_VARIABLE_CONTRIBUTION_ADJ_AMT_LC', 'Z.99.04', 'A categorizar - VC Adj', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: ajuste de VC (linha C.) - checar se ja esta dentro de UE_MP_VARIABLE_CONTRIBUTION_AMT_LC'),
    ('UE_MP_MNG_POM_POINT_AMT_LC', 'Z.99.05', 'A categorizar - POM Point', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: D.29.1.2 POM Acquisition ou D.19.4 CPA'),
    ('UE_MP_MNG_INI_AMT_LC', 'Z.99.06', 'A categorizar - Iniciativas (INI)', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: D.29.2 Demand Generation'),
    ('UE_MP_MNG_MKT_INVEST_ADJ_AMT_LC', 'Z.99.07', 'A categorizar - Mkt Invest Adj', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: D.29 Demand Gen, Branding & Others (ajuste)'),
    ('UE_MP_MNG_GNA_CORP_BU_AMT_LC', 'Z.99.08', 'A categorizar - G&A Corp BU', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: F.35 G&A BM (nivel BU); E.30.1 usa a versao SUBBU'),
    ('UE_MP_MNG_SM_CORP_BU_AMT_LC', 'Z.99.09', 'A categorizar - S&M Corp BU', 'NO_MAPEADO', 'Z. A Categorizar', 'Z.99 Campos sem mapeamento', NULL, NULL, 'RESIDUAL', 'Sugestao: F.34 S&M BM (nivel BU); E.31 usa a versao SUBBU')
  ])
)

-- 4) resultado final
SELECT
  l.PERIODO,
  l.SIT_SITE_ID,
  l.UE_MP_BU_MANAGERIAL,
  l.UE_MP_SUBBU_MANAGERIAL,
  l.UE_MP_PRODUCT_MANAGERIAL,
  COALESCE(m.TIPO_LINEA , 'RESIDUAL')                                        AS TIPO_LINEA,
  COALESCE(m.NUMERACION , 'Z.99.99')                                         AS NUMERACION,
  COALESCE(m.NOMBRE_PYL , CONCAT('A categorizar - ', l.CAMPO_UE))            AS NOMBRE_PYL,
  COALESCE(m.NIVEL_PNL  , 'NO_MAPEADO')                                      AS NIVEL_PNL,
  COALESCE(m.N1_MARGEN  , 'Z. A Categorizar')                                AS N1_MARGEN,
  COALESCE(m.N2_SUBTOTAL, 'Z.99 Campos sem mapeamento')                      AS N2_SUBTOTAL,
  m.N3_DETALLE                                                               AS N3_DETALLE,
  COALESCE(m.N4_UE      , IF(m.CAMPO_UE IS NULL, l.CAMPO_UE, NULL))          AS N4_UE,
  l.CAMPO_UE,
  COALESCE(m.SUGERENCIA , 'Campo fora do mapping - classificar manualmente')  AS SUGERENCIA,
  l.VALOR
FROM ue_long AS l
LEFT JOIN mapa AS m
  ON m.CAMPO_UE = l.CAMPO_UE
WHERE l.VALOR IS NOT NULL
  AND l.VALOR <> 0          -- comente esta linha se quiser manter os zeros
ORDER BY
  l.PERIODO, l.SIT_SITE_ID, l.UE_MP_BU_MANAGERIAL, l.UE_MP_SUBBU_MANAGERIAL,
  l.UE_MP_PRODUCT_MANAGERIAL, NUMERACION, l.CAMPO_UE
;

-- =============================================================================
-- NOTAS
-- -----------------------------------------------------------------------------
-- 1) Linhas do mapping que nao tem campo de origem na UE (ficam zeradas):
--       A.1.3.4  Insurtech Other fees
--       C.13     Shipping Ops Variable
--    (D.28 Shipping Ops Fixed usa UE_MP_SHIPPING_OPS_FIXED_AMT_LC)
-- 2) C.9.3 "Ajuste contable cbk" estava sem NIVEL_PNL no mapping -> assumido
--    PYL_DETAIL_MANAGERIAL_NEW.
-- 3) UE_MP_DISC_CBCK_PAYER_AMT_LC entra em A.1.1 Processing Fees (como no
--    mapping) e NAO em C.17.8 Descuentos.
-- 4) Splits preservados da query original:
--       SALE_TAXES / SALE_TAXES_MPOS             (TPV_SEGMENT_ID = 'Point Device Sale')
--       UE_MP_MNG_SLS_FORCE_AMT_LC / _SLS_FORCE_MPOS_  (idem)
--       UE_MP_COSTO_PLAZO_FTP_AMT_LC / SALDOS_BLOQUEADOS_MLB (MLB + DEBIT CARD)
-- 5) Versao agregada por linha do PYL (sem CAMPO_UE): envolver o SELECT final
--    (sem o ORDER BY) em:
--       SELECT PERIODO, SIT_SITE_ID, UE_MP_BU_MANAGERIAL, UE_MP_SUBBU_MANAGERIAL,
--              UE_MP_PRODUCT_MANAGERIAL, TIPO_LINEA, NUMERACION, NOMBRE_PYL,
--              NIVEL_PNL, N1_MARGEN, N2_SUBTOTAL, N3_DETALLE, N4_UE,
--              SUM(VALOR) AS VALOR
--       FROM ( ... ) GROUP BY ALL
-- 6) Conciliacao: o acumulado de TIPO_LINEA='PYL' ate cada margem deve fechar
--    com a linha 'CONTROL_UE' equivalente. Diferenca, se houver, esta nos
--    RESIDUAIS (Z.99) - foi exatamente para isso que eles existem.
-- =============================================================================
